insert into sp_users(usr_username, usr_password, usr_priority, usr_gender)values('admin', '356a192b7913b04c54574d18c28d46e6395428ab', 2, 'M');
insert into sp_flowauthorizations(fa_role, fa_fromStatus, fa_toStatus)values(1, '-', 'new');
insert into sp_flowauthorizations(fa_role, fa_fromStatus, fa_toStatus)values(2, 'new', '-');
insert into sp_flowauthorizations(fa_role, fa_fromStatus, fa_toStatus)values(2, 'new', 'trial');
insert into sp_flowauthorizations(fa_role, fa_fromStatus, fa_toStatus)values(3, 'trial', '-');
insert into sp_flowauthorizations(fa_role, fa_fromStatus, fa_toStatus)values(3, 'trial', 'final');
insert into sp_flowauthorizations(fa_role, fa_fromStatus, fa_toStatus)values(4, 'final', '-');
insert into sp_flowauthorizations(fa_role, fa_fromStatus, fa_toStatus)values(4, 'final', 'boss');
insert into sp_flowauthorizations(fa_role, fa_fromStatus, fa_toStatus)values(5, 'boss', '-');
insert into sp_flowauthorizations(fa_role, fa_fromStatus, fa_toStatus)values(5, 'boss', 'finance');
insert into sp_flowauthorizations(fa_role, fa_fromStatus, fa_toStatus)values(6, 'finance', 'logistics');
